name: deploy in GCP
run-name: '${{ github.actor }} is deploying!'
'on':
  push:
    branches:
      - main
jobs:
  deploy-bot:
    runs-on: self-hosted
    steps:
      - name: Check out the repo to the runner
        uses: actions/checkout@v4
      - name: Stop Discord bot process
        run: pm2 delete ./ecosystem.config.cjs
      - name: Create .env file
        run: |
          touch .env
          echo TOKEN=${{ secrets.TOKEN }} > .env
          echo CLIENT_ID=${{ secrets.CLIENT_ID }} >> .env
          echo GUILD_ID=${{ secrets.GUILD_ID }} >> .env
      - name: Install bun
        uses: oven-sh/setup-bun@v1
      - name: Install packages
        run: |
          bun install
      - name: Bun Build
        run: |
          bun build --entrypoints src/*.ts src/**/*.ts src/commands/**/*.ts --outdir ./dist --target bun --root src
      - name: Redeploy bot
        run: |
          pm2 start ./ecosystem.config.cjs
