name: deploy in GCP
run-name: ${{ github.actor }} is deploying!
on: [push]

jobs:
  deploy-bot:
    runs-on: self-hosted
    steps:
      - name: Stop Discord bot process
        run: pm2 stop ~/ecosystem.config.js
      
      - name: Check out the repo to the runner
        uses: actions/checkout@v4.1.1

      - name: Redeploy bot
        run: |
          npm ci
          pm2 start ~/ecosystem.config.js
