name: deploy in GCP
run-name: ${{ github.actor }} is deploying!
on: [push]

jobs:
  deploy-bot:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4.0.0
        with:
          node-version: '18.18.2'
      - run: npm ci 
