name: deploy in GCP
run-name: ${{ github.actor }} is deploying!
on:
  push:
    branches:
      - main

jobs:
  deploy-bot:
    runs-on: self-hosted
    steps:
      - name: Stop Discord bot process
        run: pm2 stop ~/ecosystem.config.js
      
      - name: Check out the repo to the runner
        uses: actions/checkout@v4.1.1

      - name: Create .env file
        run: |
          touch .env
          echo TOKEN=${{ secrets.TOKEN }} > .env
          echo CLIENT_ID=${{ secrets.CLIENT_ID }} >> .env
          echo GUILD_ID=${{ secrets.GUILD_ID }} >> .env

      - name: Redeploy bot
        run: |
          npm i
          pm2 start ~/ecosystem.config.js
